---
kind: pipeline
type: docker
name: bionic/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb
  image: arescentral/deb:bionic
  settings:
    dir: bionic

- name: check
  image: ubuntu:bionic
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: buster/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb
  image: arescentral/deb:buster
  settings:
    dir: buster

- name: check
  image: debian:buster-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: buster/arm

platform:
  os: linux
  arch: arm

steps:
- name: deb
  image: arescentral/deb:buster
  settings:
    dir: buster

- name: check
  image: debian@sha256:43e8691b4e25f4b0fd0f10bca8ea11b9f0578b0e5d2fe3b085290455dd07c0b6
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: buster/arm64

platform:
  os: linux
  arch: arm64

steps:
- name: deb
  image: arescentral/deb:buster
  settings:
    dir: buster

- name: check
  image: debian:buster-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: focal/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb
  image: arescentral/deb:focal
  settings:
    dir: focal

- name: check
  image: ubuntu:focal
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: stretch/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb
  image: arescentral/deb:stretch
  settings:
    dir: stretch

- name: check
  image: debian:stretch-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: stretch/arm

platform:
  os: linux
  arch: arm

steps:
- name: deb
  image: arescentral/deb:stretch
  settings:
    dir: stretch

- name: check
  image: debian@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: stretch/arm64

platform:
  os: linux
  arch: arm64

steps:
- name: deb
  image: arescentral/deb:stretch
  settings:
    dir: stretch

- name: check
  image: debian:stretch-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: xenial/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb
  image: arescentral/deb:xenial
  settings:
    dir: xenial

- name: check
  image: ubuntu:xenial
  commands:
  - uname -a
  - dpkg -i ninja-build_*.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

...
