---
kind: pipeline
type: docker
name: debian/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb/buster
  image: arescentral/deb-buster
  settings:
    dir: buster

- name: check/buster
  image: debian:buster-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*buster_amd64.deb
  - ninja --version

- name: deb/stretch
  image: arescentral/deb-stretch
  settings:
    dir: stretch

- name: check/stretch
  image: debian:stretch-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*stretch_amd64.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    file_exists: skip
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: debian/arm64

platform:
  os: linux
  arch: arm64

steps:
- name: deb/buster
  image: arescentral/deb-buster
  settings:
    dir: buster

- name: check/buster
  image: debian:buster-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*buster_arm64.deb
  - ninja --version

- name: deb/stretch
  image: arescentral/deb-stretch
  settings:
    dir: stretch

- name: check/stretch
  image: debian:stretch-slim
  commands:
  - uname -a
  - dpkg -i ninja-build_*stretch_arm64.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    file_exists: skip
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: debian/arm

platform:
  os: linux
  arch: arm

steps:
- name: deb/buster
  image: arescentral/deb-buster
  settings:
    dir: buster

- name: check/buster
  image: debian@sha256:43e8691b4e25f4b0fd0f10bca8ea11b9f0578b0e5d2fe3b085290455dd07c0b6
  commands:
  - uname -a
  - dpkg -i ninja-build_*buster_arm.deb
  - ninja --version

- name: deb/stretch
  image: arescentral/deb-stretch
  settings:
    dir: stretch

- name: check/stretch
  image: debian@sha256:6aac188bc15bac908192685068ef8512a2e51b5eb1138b663e9e33d1d98ade4b
  commands:
  - uname -a
  - dpkg -i ninja-build_*stretch_arm.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    file_exists: skip
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

---
kind: pipeline
type: docker
name: ubuntu/amd64

platform:
  os: linux
  arch: amd64

steps:
- name: deb/focal
  image: arescentral/deb-focal
  settings:
    dir: focal

- name: check/focal
  image: ubuntu:focal
  commands:
  - uname -a
  - dpkg -i ninja-build_*focal_amd64.deb
  - ninja --version

- name: deb/bionic
  image: arescentral/deb-bionic
  settings:
    dir: bionic

- name: check/bionic
  image: ubuntu:bionic
  commands:
  - uname -a
  - dpkg -i ninja-build_*bionic_amd64.deb
  - ninja --version

- name: deb/xenial
  image: arescentral/deb-xenial
  settings:
    dir: xenial

- name: check/xenial
  image: ubuntu:xenial
  commands:
  - uname -a
  - dpkg -i ninja-build_*xenial_amd64.deb
  - ninja --version

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    file_exists: skip
    files:
    - ninja-build_*.deb
    - ninja-build_*.dsc
  when:
    event:
    - tag

...
