#!/usr/bin/env python3

import os
import json
import shutil
import urllib.request

def main():
    try:
        shutil.rmtree("dist")
    except FileNotFoundError:
        pass
    os.mkdir("dist")

    with open("release.json") as f:
        release = json.load(f)
    version = release["tag_name"][1:]
    path = os.path.join("dist", "ninja-%s.tar.gz" % version)
    url = release["html_url"].replace("releases/tag", "archive") + ".tar.gz"
    with urllib.request.urlopen(url) as src:
        with open(path, "wb") as dst:
            shutil.copyfileobj(src, dst)
    print("Downloaded %s" % path)


if __name__ == "__main__":
    main()
