#!/usr/bin/env python3

import os
import json
import subprocess
import urllib.request

URL = "https://api.github.com/repos/ninja-build/ninja/releases/latest"


def main():
    with urllib.request.urlopen(URL) as f:
        release = json.load(f)
    with open("release.json", "w") as f:
        json.dump(release, f, indent=2)
    print("downloaded release.json (%s)" % release["tag_name"])

    tag_name = release["tag_name"].lstrip("v")
    old_version = changelog_version()
    if tag_name == old_version.split("-")[0]:
        print("already %s" % old_version)
        return
    new_version = "%s-1" % tag_name
    update_changelog(new_version, release["body"])
    print("%s => %s" % (old_version, new_version))


def changelog_version():
    return subprocess.check_output([
        "dpkg-parsechangelog",
        "-S",
        "Version",
    ]).strip().decode("utf-8")


def update_changelog(version, text):
    subprocess.check_call([
        "dch",
        "--newversion=%s" % version,
        "--distribution=stable",
        "--force-distribution",
        text,
    ])


if __name__ == "__main__":
    main()
